[tools]
bun = "latest"
dotnet = "latest"
eza = "latest"
go = "latest"
java = "openjdk-25.0.2"
neovim = "0.11"
node = "latest"
python = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
zig = "latest"
gemini-cli = "latest"
