return {
	{
		"nvim-treesitter/nvim-treesitter",
		branch = "main",
		event = { "BufReadPre", "BufNewFile" },
		build = ":TSUpdate",
		opts = {
			ensure_installed = {
				"json",
				"javascript",
				"typescript",
				"tsx",
				"yaml",
				"html",
				"css",
				"markdown",
				"markdown_inline",
				"bash",
				"lua",
				"vim",
				"gitignore",
				"c",
				"go",
				"python",
				"c_sharp",
				"sql",
				"gosum",
				"gomod",
				"dockerfile",
				"rust",
			},
			auto_install = true,
			ignore_install = {},
			highlight = {
				enable = true,
			},
			indent = { enable = true, disable = { "python" } },
			autotag = {
				enable = true,
			},
		},
	},
	{
		"windwp/nvim-ts-autotag",
		ft = {
			"html",
			"tsx",
			"jsx",
			"markdown",
			"javascript",
			"typescript",
			"javascriptreact",
			"typescriptreact",
			"xml",
		},
		config = function()
			require("nvim-ts-autotag").setup()
		end,
	},
}
